import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton} from '@clerk/nextjs'
import {NextUIProvider} from "@nextui-org/react";
import { redirect } from "next/navigation";

export const metadata = {
  title: "TanAahara",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider afterSignOutUrl="/sign-in">
      <html lang="en">
        <body className="">
          <NextUIProvider>
            <main className="container mx-auto">
              {children}
            </main>
          </NextUIProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
